[package]
name = "http_tester"
version = "0.1.0"
authors = ["Atul Sharma <asharma@sw-at.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.5"
